# List of states
States = ['Punjab', 
          'Haryana', 
          'Uttarakhand',
          'Uttar_Pradesh',
          'Madhya_Pradesh',
          'Rajasthan',
          'Bihar',
          'Chhattisgarh',
          'Jharkhand',
          'Odisha',
          'Maharashtra',
          'Telangana',
          'Andhra_Pradesh',
          'Goa',
          'Karnataka',
          'Tamil_Nadu',
          'Kerala',
          'West_Bengal',
          'Sikkim',
          'Arunachal_Pradesh',
          'Assam',
          'Manipur',
          'Mizoram',
          'Meghalaya',
          'Nagaland',
          'Tripura']

# List of UTs
UTs = ['NCT_Delhi',
       'Andaman_Nicobar_Islands',
       'Dadra_Nagar_Haveli_Daman_Diu',
       'Jammu_Kashmir',
       'Ladakh',
       'Puducherry',
       #'Chandigarh',
       #'Lakshadweep'
    ]